<?php

namespace core\Exceptions;

class Exception extends \Exception implements \Stringable
{
    public function __toString(): string
    {
        parent::__toString(); // TODO: Change the autogenerated stub
    }
}